-- list all orders along with corresponding customer name and city

select o.orderid, c. customerid, c.companyname, c.city  from orders o join customers c on o.customerID = 
c.customerID;

-- calculate the total quantity ordered for each product

select p.productID, p.productName, sum(od.quantity) as product_quantity
from products p join order_details od on p.productID = od.productID
group by productID
order by product_quantity desc;

-- Percentage of total revenue by product
select p.productID, p.productName, 
-- sum(od.quantity * od.unitprice * (1- discount)) as product_revenue,
round((sum(od.quantity * od.unitprice * (1- discount))/
(select sum(od2.quantity * od2.unitprice * (1- discount)) as total_revenue from order_details od2)) * 100, 2) as Perc_revn
from products p join order_details od on p.productID = od.productID
group by productID
order by perc_revn desc;

-- find top 5 customers with highest total senpding on orders,

select o.customerid, sum(od.quantity * od.unitprice * (1- discount)) as customer_spend
from orders o join order_details od on o.orderID = od.orderID
group by o.customerid
order by customer_spend desc limit 5;

-- Update the discount of orders for discontinued products to zero

update order_details
set discount = 0
where productid in 
 (select productID from products
where discontinued = 1);


-- Calculate the average frieght cost for each shipper and show only those with above avrage cost

Select o.shipperid, avg(o.freight) as avg_freight 
from orders o
group by o.shipperid
having  avg_freight > (select avg(o.freight) from orders o);

-- Find Monthly sales revenue generated by each employee.alter

Select o.employeeId, month(o.orderdate) as Month_, year(o.orderdate) as Year_, 
sum(od.unitprice * od.quantity*(1- od.discount)) as Monthly_sales
from orders o join order_details od on o.orderID=od.orderID
group by o.employeeID, Year_, month_
order by o.employeeID, Year_, month_;

-- Identify which shipping company handles the most orders where the total order valuve exceed $500

with above_500_orders as 
	(Select od.orderId, sum(od.unitprice * od.quantity*(1- od.discount)) as total_order_value
	from order_details od
	group by od.orderID
	having total_order_value > 500)
select o.shipperid, count(*) as high_value_orders
from orders	o join above_500_orders a5o on o.orderid = a5o.orderid
group by shipperID
order by high_value_orders desc; 

-- identify which employee has the highest sales (in terms of revenue) in each product category.

with cat_emp_sales as
	(select cat.categoryid, e.employeeID, sum(od.unitprice * od.quantity*(1- od.discount)) as emp_cat_sales
	from categories as cat join products p on cat.categoryid = p.categoryid
	join order_details od on od.productID = p.productID
	join orders o on o.orderid = od.orderID
	join employees e on e.employeeID = o.employeeID
	group by cat.categoryid, e.employeeID
	order by cat.categoryid, e.employeeID
    )
    select ces.categoryID, ces.employeeID, e.employeeName
    from cat_emp_sales ces join 
		(select ces2.categoryID, max(emp_cat_sales) as max_sales
        from cat_emp_sales ces2
        group by ces2.categoryID 
        ) as cat_max_sales
        on ces.categoryID = cat_max_sales.categoryID and ces.emp_cat_sales = cat_max_sales.max_sales
    join employees e on e.employeeID = ces.employeeID
    order by ces.categoryID, ces.employeeID;
